# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb6f9460120e691186bd0da28006d4b7eb7ffc5d6e93139c17fd063d6bce92f55afed0654e83695703230ebd4a1643e020eecf30602437445df928888eecb49

test:
  secret_key_base: f94b1b87e6f0ab08e2b0b7b152c1bc49d2395a3f77716357fcb893e3d4693056127df0de45ec229f90eb454b7cb100076948b6a2c91caa3d941163ede2271706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
